# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/centos7"
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = 'qemu:///system'
    libvirt.storage_pool_path = '/var/lib/libvirt/images'
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=4', 'tcp', 'nolock']
    }
  end

  config.vm.synced_folder "../../ansible/", "/vagrant/ansible",
    type: "nfs", nfs_version: 4, nfs_udp: false

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/sandbox.yml"
    ansible.groups = {
      "sandbox" => ["default"]
    }
  end
end
