---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/metallb/metallb

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 10m0s
  path: ./config/native
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
