---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  path: ./apps/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  path: ./apps/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
