---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb-git
  namespace: metallb
spec:
  interval: 10m0s
  ref:
    semver: "0.13.9"
  url: https://github.com/metallb/metallb

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 10m0s
  path: ./config/native
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: metallb
spec:
  dependsOn:
    - name: metallb
  interval: 10m0s
  path: ./apps/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
