---
- name: set selinux to allow http traffic
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: install nginx
  package:
    name:
      - nginx
    state: present
  notify: reload systemd

- name: generate nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: generate site-specific config
  template:
    src: "templates/{{ nginx_config_file }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_config_file }}.conf"
  notify: restart nginx

- name: configure nginx to run on startup
  service:
    name: nginx
    state: started
    enabled: true
  notify: reload systemd

- name: open firewall to nginx
  firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
  notify: reload firewall
