# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "sbx1" do |app|
    app.vm.box = "generic/fedora35"
    app.vm.hostname = "sbx1"
    app.vm.network :private_network, ip: "192.168.56.21"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/sandbox.yml"
    ansible.groups = {
      "sandbox" => ["sbx1"]
    }
  end
end
