---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: local-path-provisioner
      app.kubernetes.io/managed-by: kustomize
metadata:
  name: local-path-storage
namespace: local-path-storage
resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
