---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: local-path-provisioner-labels
labels:
  app.kubernetes.io/name: local-path-provisioner
  app.kubernetes.io/instance: local-path-provisioner
  app.kubernetes.io/managed-by: kustomize
fieldSpecs:
  - path: metadata/labels
    create: true
