---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
spec:
  secretName: jenkins-tls
  usages:
    - server auth
    - client auth
  dnsNames:
    - "jenkins.127.0.0.1.nip.io"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
