# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load common configs
vagrantfile_common = "../common/vagrantfile-common"
load vagrantfile_common if File.exists?(vagrantfile_common)

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "scm1" do |app|
    app.vm.network :public_network, ip: "192.168.1.15"
    app.vm.hostname = "scm1"
    app.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/gitea.yml"
      ansible.groups = { "gitea" => ["scm1"] }
    end
  end
end
