---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: calico
      app.kubernetes.io/managed-by: kustomize
resources:
  - https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calico.yaml
  - https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calicoctl.yaml
