---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: calico
      app.kubernetes.io/managed-by: kustomize
metadata:
  name: calico
resources:
  - https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/calico.yaml
  # - https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/calicoctl.yaml
