# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load common configs
vagrantfile_common = "../common/vagrantfile-common"
load vagrantfile_common if File.exists?(vagrantfile_common)

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "jkm1" do |app|
    app.vm.hostname = "build.test"
    app.vm.network :private_network, ip: "192.168.1.10"
  end

  # create multiple jenkins agents
  N=2
  (1..N).each do |i|
    config.vm.define "jka#{i}" do |app|
      app.vm.hostname = "jka#{i}"
      app.vm.network :private_network, ip: "192.168.1.1#{i}"
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/jenkins.yml"
    ansible.groups = { 
      "jenkins_master" => ["jkm1"],
      "jenkins_agent" => ["jka1", "jka2"]
    }
  end
end
