# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "generic/fedora35"
    config.vm.hostname = "ansible"
    config.vm.network :private_network, ip: "192.168.56.10"
  
    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
      sudo echo -e 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
      sudo restorecon -Rv /etc
      sudo timedatectl set-local-rtc 0
      sudo timedatectl set-ntp true
      sudo timedatectl set-timezone Australia/Queensland
    SHELL
  end
  