---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.25.1
      sourceRef:
        kind: HelmRepository
        name: tigera-operator-chart
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
