---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tigera-operator-chart
  namespace: flux-system
spec:
  interval: 1h
  url: https://projectcalico.docs.tigera.io/charts
