---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: docker-minikube
  namespace: metallb-system
spec:
  # Bind to the container network:
  # docker network inspect -f '{{.IPAM.Config}}' minikube
  # https://kind.sigs.k8s.io/docs/user/loadbalancer/
  addresses:
    - 192.168.49.245-192.168.49.254
  # https://metallb.org/configuration/_advanced_ipaddresspool_configuration/#handling-buggy-networks
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: docker-minikube-arp
  namespace: metallb-system
spec:
  ipAddressPools:
    - docker-minikube
