---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: metallb
      app.kubernetes.io/managed-by: kustomize
metadata:
  name: metallb
namespace: metallb-system
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml
