---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
spec:
  secretName: vault-tls
  usages:
    - server auth
    - client auth
  dnsNames:
    - "vault.127.0.0.1.nip.io"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
