---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vault
namespace: vault

resources:
  - namespace.yaml
  - ingress.yaml
  - certificate.yaml

helmCharts:
  - name: vault
    includeCRDs: false
    releaseName: vault
    # chart version
    version: 0.27.0
    repo: https://helm.releases.hashicorp.com
    valuesFile: values.yaml
