---
server:
  ha:
    enabled: true
    raft:
      enabled: true

  image:
    tag: "1.15.2"

  statefulSet:
    securityContext:
      container:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL

  updateStrategyType: "RollingUpdate"

injector:
  enabled: false
