---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: calico-operator
spec:
  interval: 10m0s
  url: https://projectcalico.docs.tigera.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico-operator
spec:
  interval: 10m0s
  chart:
    spec:
      chart: tigera-operator
      version: v3.25.1
      sourceRef:
        kind: HelmRepository
        name: calico-operator
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
